config/routes.rb
Rails.application.routes.draw do
  root :to => "lyrics#index"
  resources :lyrics

end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  before_action :set_lyric, only: [:show, :edit, :update, :destroy]

  # GET /lyrics
  # GET /lyrics.json
  def index
    @lyrics = Lyric.all
    require 'open-uri'
    
    if params[:artist] and params[:song]
      artist = params[:artist].split(' ').join('-')
      song = params[:song].split(' ').join('-')
      @query = artist + "-" + song + "-lyrics"
    end
    
    if params[:genius]
     @query = params[:genius]
    end

    if !@query
      @query = "Eminem-Rap-God-Lyrics"
    end
    @doc = Nokogiri::HTML(open("http://genius.com/#{@query}"))
    @words = @doc.css("div[class=song_body-lyrics]").css("p");
    rescue OpenURI::HTTPError => e
    if e.message == '404 Not Found'
      redirect_to '/'
    else
      raise e
    end
    
  end

  # GET /lyrics/1
  # GET /lyrics/1.json
  def show
  end

  # GET /lyrics/new
  def new
    @lyric = Lyric.new
  end

  # GET /lyrics/1/edit
  def edit
  end

  # POST /lyrics
  # POST /lyrics.json
  def create
    @lyric = Lyric.new(lyric_params)

    respond_to do |format|
      if @lyric.save
        format.html { redirect_to @lyric, notice: 'Lyric was successfully created.' }
        format.json { render :show, status: :created, location: @lyric }
      else
        format.html { render :new }
        format.json { render json: @lyric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lyrics/1
  # PATCH/PUT /lyrics/1.json
  def update
    respond_to do |format|
      if @lyric.update(lyric_params)
        format.html { redirect_to @lyric, notice: 'Lyric was successfully updated.' }
        format.json { render :show, status: :ok, location: @lyric }
      else
        format.html { render :edit }
        format.json { render json: @lyric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lyrics/1
  # DELETE /lyrics/1.json
  def destroy
    @lyric.destroy
    respond_to do |format|
      format.html { redirect_to lyrics_url, notice: 'Lyric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lyric
      @lyric = Lyric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lyric_params
      params.fetch(:lyric, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lyrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://unpkg.com/nlp_compromise@latest/builds/nlp_compromise.min.js" %>
  <%= javascript_include_tag "https://d3js.org/d3.v3.min.js" %>



  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lyrics/_form.html.erb
<%= form_for(@lyric) do |f| %>
  <% if @lyric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lyric.errors.count, "error") %> prohibited this lyric from being saved:</h2>

      <ul>
      <% @lyric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lyrics/edit.html.erb
<h1>Editing Lyric</h1>

<%= render 'form' %>

<%= link_to 'Show', @lyric %> |
<%= link_to 'Back', lyrics_path %>

app/views/lyrics/index.html.erb
<p class="lyrics">
<% @words.each do |line| %>
<%= line.text.strip %><br>
<% end %>
</p>
<h2>
<%= @query.split('-').join(' ').titleize %>
</h2>

<div class="guts"></div>

<div class="search">
<%= form_tag("/", method: "get") do %>
  <%= label_tag(:q, "Artist:") %>
  <%= text_field_tag(:artist) %>
  <%= label_tag(:song, "Song:") %>
  <%= text_field_tag(:song) %>
  <%= submit_tag("Hit it") %>
<% end %>

<p>?genius=FirstName-LastName-Song-Name-Lyrics</p>
</div>

app/views/lyrics/new.html.erb
<h1>New Lyric</h1>

<%= render 'form' %>

<%= link_to 'Back', lyrics_path %>

app/views/lyrics/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lyric_path(@lyric) %> |
<%= link_to 'Back', lyrics_path %>